#!/usr/bin/env python3
"""Animate evolutionary populations generation by generation over an objective contour."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg", force=True)

import matplotlib.pyplot as plt
from matplotlib.animation import FFMpegWriter
from matplotlib.animation import FuncAnimation
from matplotlib.animation import PillowWriter
from matplotlib.colors import Normalize
import numpy as np
import pandas as pd

from functions_2d import get_bounds, get_function, infer_bounds_from_points


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Animate evolutionary populations across generations from history.csv."
    )
    parser.add_argument("--history", required=True, help="CSV generated by extract_history.py.")
    parser.add_argument("--out", required=True, help="Output animation path (.gif or .mp4).")
    parser.add_argument(
        "--pop-size",
        type=int,
        default=None,
        help="Population size used to reconstruct generation from eval_index when needed.",
    )
    parser.add_argument("--function", default=None, help="Function name override.")
    parser.add_argument(
        "--bounds",
        nargs=4,
        type=float,
        metavar=("xmin", "xmax", "ymin", "ymax"),
        default=None,
        help="Override plotting bounds.",
    )
    parser.add_argument("--grid", type=int, default=320, help="Contour grid resolution.")
    parser.add_argument("--fps", type=int, default=20, help="Animation FPS.")
    parser.add_argument("--top-k", type=int, default=5, help="Number of best individuals to highlight.")
    parser.add_argument(
        "--max-gens",
        type=int,
        default=None,
        help="Optional cap on the number of generations to animate, starting from generation 0.",
    )
    parser.add_argument(
        "--trail",
        action="store_true",
        help="Show a faint trail of best-so-far positions across previous generations.",
    )
    return parser.parse_args()


def load_history(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    if frame.empty:
        raise ValueError("History CSV is empty.")
    return frame


def infer_function(frame: pd.DataFrame, override: str | None) -> str:
    if override:
        return override
    if "function" not in frame.columns:
        raise ValueError("Could not infer function from CSV. Use --function to specify one explicitly.")
    names = frame["function"].fillna("").astype(str).str.strip()
    non_empty = names[names != ""]
    if non_empty.empty:
        raise ValueError("Could not infer function from CSV. Use --function to specify one explicitly.")
    return str(non_empty.iloc[0])


def prepare_history(frame: pd.DataFrame, pop_size: int | None) -> pd.DataFrame:
    prepared = frame.copy()
    prepared["x"] = pd.to_numeric(prepared.get("x"), errors="coerce")
    prepared["y"] = pd.to_numeric(prepared.get("y"), errors="coerce")
    prepared["objective"] = pd.to_numeric(prepared.get("objective"), errors="coerce")
    prepared["eval_index"] = pd.to_numeric(prepared.get("eval_index"), errors="coerce")

    if "generation" in prepared.columns:
        prepared["generation"] = pd.to_numeric(prepared["generation"], errors="coerce")
    else:
        if pop_size is None:
            raise ValueError(
                "History CSV does not contain a generation column. Provide --pop-size to reconstruct generations."
            )
        if pop_size < 1:
            raise ValueError("--pop-size must be >= 1")
        prepared["generation"] = np.floor_divide(prepared["eval_index"], pop_size)

    prepared = prepared.dropna(subset=["x", "y", "generation"]).copy()
    if prepared.empty:
        raise ValueError("No rows with numeric x/y and generation information were found.")

    prepared["generation"] = prepared["generation"].astype(int)
    return prepared


def infer_bounds(
    frame: pd.DataFrame,
    function_name: str,
    override: tuple[float, float, float, float] | None,
) -> tuple[float, float, float, float]:
    if override is not None:
        return override
    try:
        return get_bounds(function_name)
    except ValueError:
        pass
    return infer_bounds_from_points(frame["x"].to_numpy(dtype=float), frame["y"].to_numpy(dtype=float))


def sorted_generations(frame: pd.DataFrame, max_gens: int | None) -> list[int]:
    generations = sorted(frame["generation"].unique().tolist())
    if not generations:
        raise ValueError("No generations were found in history.")
    if max_gens is not None:
        if max_gens < 1:
            raise ValueError("--max-gens must be >= 1")
        generations = generations[:max_gens]
    return [int(g) for g in generations]


def select_top_k(frame: pd.DataFrame, top_k: int) -> pd.DataFrame:
    if top_k <= 0:
        return frame.iloc[0:0].copy()
    ordered = frame.sort_values(by="objective", ascending=True, na_position="last", kind="mergesort")
    return ordered.head(top_k).copy()


def best_so_far_rows(frame: pd.DataFrame, generations: list[int]) -> list[pd.Series | None]:
    results: list[pd.Series | None] = []
    for generation in generations:
        candidates = frame.loc[frame["generation"] <= generation].dropna(subset=["objective"]).copy()
        if candidates.empty:
            results.append(None)
            continue
        ordered = candidates.sort_values(by="objective", ascending=True, na_position="last", kind="mergesort")
        results.append(ordered.iloc[0])
    return results


def main() -> int:
    args = parse_args()
    history = load_history(Path(args.history))
    prepared = prepare_history(history, args.pop_size)
    function_name = infer_function(history, args.function)
    fn = get_function(function_name)

    bounds_override = tuple(args.bounds) if args.bounds is not None else None
    xmin, xmax, ymin, ymax = infer_bounds(prepared, function_name, bounds_override)
    generations = sorted_generations(prepared, args.max_gens)

    x_grid = np.linspace(xmin, xmax, args.grid)
    y_grid = np.linspace(ymin, ymax, args.grid)
    xx, yy = np.meshgrid(x_grid, y_grid)
    zz = fn(xx, yy)

    frames: list[pd.DataFrame] = [
        prepared.loc[prepared["generation"] == generation].copy() for generation in generations
    ]
    top_frames: list[pd.DataFrame] = [select_top_k(frame, args.top_k) for frame in frames]
    best_rows = best_so_far_rows(prepared, generations)

    objective_values = prepared["objective"].to_numpy(dtype=float)
    finite_objectives = objective_values[np.isfinite(objective_values)]
    if finite_objectives.size == 0:
        raise ValueError("No numeric objective values were found in history.")
    norm = Normalize(vmin=float(np.min(finite_objectives)), vmax=float(np.max(finite_objectives)))

    fig, ax = plt.subplots(figsize=(9, 7))
    ax.contourf(xx, yy, zz, levels=50)
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, ymax)

    population = ax.scatter(
        [],
        [],
        c=[],
        cmap="viridis",
        norm=norm,
        s=55,
        alpha=0.9,
        edgecolors="black",
        linewidths=0.6,
        label="population",
    )
    fig.colorbar(population, ax=ax, label="objective")

    top_marker = ax.scatter(
        [],
        [],
        marker="*",
        s=220,
        facecolors="gold",
        edgecolors="black",
        linewidths=0.9,
        label=f"top {max(0, args.top_k)}",
    )
    best_marker = ax.scatter(
        [],
        [],
        marker="o",
        s=160,
        facecolors="white",
        edgecolors="black",
        linewidths=1.2,
        label="best-so-far",
    )
    trail_line, = ax.plot([], [], color="white", alpha=0.45, linewidth=1.4, linestyle="--", label="best trail")
    title_text = ax.set_title("")
    ax.legend(loc="best")

    total_frames = len(generations)

    def empty_offsets() -> np.ndarray:
        return np.empty((0, 2), dtype=float)

    def set_scatter(collection: plt.Collection, frame: pd.DataFrame) -> None:
        if frame.empty:
            collection.set_offsets(empty_offsets())
            if hasattr(collection, "set_array"):
                collection.set_array(np.asarray([], dtype=float))
            return
        offsets = frame[["x", "y"]].to_numpy(dtype=float)
        collection.set_offsets(offsets)
        if hasattr(collection, "set_array"):
            collection.set_array(frame["objective"].to_numpy(dtype=float))

    def init() -> tuple:
        population.set_offsets(empty_offsets())
        population.set_array(np.asarray([], dtype=float))
        top_marker.set_offsets(empty_offsets())
        best_marker.set_offsets(empty_offsets())
        trail_line.set_data([], [])
        title_text.set_text("")
        return (population, top_marker, best_marker, trail_line, title_text)

    def update(frame_number: int) -> tuple:
        generation = generations[frame_number]
        generation_frame = frames[frame_number]
        top_frame = top_frames[frame_number]
        best_row = best_rows[frame_number]

        set_scatter(population, generation_frame)

        if top_frame.empty:
            top_marker.set_offsets(empty_offsets())
        else:
            top_marker.set_offsets(top_frame[["x", "y"]].to_numpy(dtype=float))

        if best_row is None:
            best_marker.set_offsets(empty_offsets())
            trail_line.set_data([], [])
        else:
            best_marker.set_offsets(np.array([[float(best_row["x"]), float(best_row["y"])]], dtype=float))
            if args.trail:
                trail_points = [
                    (float(row["x"]), float(row["y"]))
                    for row in best_rows[: frame_number + 1]
                    if row is not None
                ]
                if trail_points:
                    trail = np.asarray(trail_points, dtype=float)
                    trail_line.set_data(trail[:, 0], trail[:, 1])
                else:
                    trail_line.set_data([], [])
            else:
                trail_line.set_data([], [])

        title_text.set_text(f"{function_name} Gen {generation} / {generations[-1]}")
        return (population, top_marker, best_marker, trail_line, title_text)

    anim = FuncAnimation(
        fig,
        update,
        init_func=init,
        frames=total_frames,
        interval=max(1, int(round(1000.0 / max(1, args.fps)))),
        blit=True,
    )

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    suffix = out_path.suffix.lower()
    if suffix == ".gif":
        writer = PillowWriter(fps=args.fps)
    elif suffix == ".mp4":
        writer = FFMpegWriter(fps=args.fps)
    else:
        raise ValueError("Output extension must be .gif or .mp4")

    try:
        anim.save(out_path, writer=writer)
    except Exception as exc:
        if suffix == ".mp4":
            raise RuntimeError(
                "Failed to write MP4. Ensure ffmpeg is installed and discoverable by matplotlib, "
                "or use a .gif output path."
            ) from exc
        raise

    print(f"Saved animation: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
