#!/usr/bin/env python3
"""Animate synchronized 3D population, convergence, and diversity panels."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg", force=True)

import matplotlib.pyplot as plt
from matplotlib.animation import FFMpegWriter
from matplotlib.animation import FuncAnimation
from matplotlib.animation import PillowWriter
from matplotlib.gridspec import GridSpec
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
import numpy as np
import pandas as pd

from functions_2d import get_bounds, get_function, infer_bounds_from_points
from output_paths import resolve_output_path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Animate a dashboard with 3D population, convergence, and diversity panels."
    )
    parser.add_argument("--history", required=True, help="CSV generated by extract_history.py.")
    parser.add_argument("--out", required=True, help="Output animation path (.gif or .mp4).")
    parser.add_argument(
        "--pop-size",
        type=int,
        default=None,
        help="Population size used to reconstruct generation from eval_index when needed.",
    )
    parser.add_argument("--function", default=None, help="Function name override.")
    parser.add_argument(
        "--bounds",
        nargs=4,
        type=float,
        metavar=("xmin", "xmax", "ymin", "ymax"),
        default=None,
        help="Override plotting bounds.",
    )
    parser.add_argument("--grid", type=int, default=150, help="Surface grid resolution.")
    parser.add_argument("--fps", type=int, default=10, help="Animation FPS.")
    parser.add_argument("--top-k", type=int, default=5, help="Number of best individuals to highlight.")
    parser.add_argument(
        "--max-gens",
        type=int,
        default=None,
        help="Optional cap on the number of generations to animate, starting from generation 0.",
    )
    parser.add_argument("--elev", type=float, default=48.0, help="Initial elevation angle in degrees.")
    parser.add_argument("--azim", type=float, default=-60.0, help="Initial azimuth angle in degrees.")
    parser.add_argument("--rotate", action="store_true", help="Rotate the 3D camera slowly during the animation.")
    return parser.parse_args(argv)


def load_history(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    if frame.empty:
        raise ValueError("History CSV is empty.")
    return frame


def infer_function(frame: pd.DataFrame, override: str | None) -> str:
    if override:
        return override
    if "function" not in frame.columns:
        raise ValueError("Could not infer function from CSV. Use --function to specify one explicitly.")
    names = frame["function"].fillna("").astype(str).str.strip()
    non_empty = names[names != ""]
    if non_empty.empty:
        raise ValueError("Could not infer function from CSV. Use --function to specify one explicitly.")
    return str(non_empty.iloc[0])


def prepare_history(frame: pd.DataFrame, pop_size: int | None) -> pd.DataFrame:
    prepared = frame.copy()
    prepared["x"] = pd.to_numeric(prepared.get("x"), errors="coerce")
    prepared["y"] = pd.to_numeric(prepared.get("y"), errors="coerce")
    prepared["objective"] = pd.to_numeric(prepared.get("objective"), errors="coerce")
    prepared["eval_index"] = pd.to_numeric(prepared.get("eval_index"), errors="coerce")

    if "generation" in prepared.columns:
        prepared["generation"] = pd.to_numeric(prepared["generation"], errors="coerce")
    else:
        if pop_size is None:
            raise ValueError(
                "History CSV does not contain a generation column. Provide --pop-size to reconstruct generations."
            )
        if pop_size < 1:
            raise ValueError("--pop-size must be >= 1")
        prepared["generation"] = np.floor_divide(prepared["eval_index"], pop_size)

    prepared = prepared.dropna(subset=["x", "y", "objective", "generation"]).copy()
    if prepared.empty:
        raise ValueError("No rows with numeric x/y/objective and generation information were found.")

    prepared["generation"] = prepared["generation"].astype(int)
    return prepared


def infer_bounds(
    frame: pd.DataFrame,
    function_name: str,
    override: tuple[float, float, float, float] | None,
) -> tuple[float, float, float, float]:
    if override is not None:
        return override
    try:
        return get_bounds(function_name)
    except ValueError:
        pass
    return infer_bounds_from_points(frame["x"].to_numpy(dtype=float), frame["y"].to_numpy(dtype=float))


def sorted_generations(frame: pd.DataFrame, max_gens: int | None) -> list[int]:
    generations = sorted(frame["generation"].unique().tolist())
    if not generations:
        raise ValueError("No generations were found in history.")
    if max_gens is not None:
        if max_gens < 1:
            raise ValueError("--max-gens must be >= 1")
        generations = generations[:max_gens]
    return [int(g) for g in generations]


def select_top_k(frame: pd.DataFrame, top_k: int) -> pd.DataFrame:
    if top_k <= 0:
        return frame.iloc[0:0].copy()
    ordered = frame.sort_values(by="objective", ascending=True, na_position="last", kind="mergesort")
    return ordered.head(top_k).copy()


def best_so_far_rows(frame: pd.DataFrame, generations: list[int]) -> list[pd.Series | None]:
    results: list[pd.Series | None] = []
    for generation in generations:
        candidates = frame.loc[frame["generation"] <= generation].copy()
        if candidates.empty:
            results.append(None)
            continue
        ordered = candidates.sort_values(by="objective", ascending=True, na_position="last", kind="mergesort")
        results.append(ordered.iloc[0])
    return results


def build_convergence_stats(frame: pd.DataFrame) -> pd.DataFrame:
    stats = (
        frame.groupby("generation", sort=True)["objective"]
        .agg(best="min", median="median", worst="max")
        .reset_index()
    )
    stats["best_so_far"] = stats["best"].cummin()
    return stats


def compute_diversity(group: pd.DataFrame) -> dict[str, float]:
    valid = group.dropna(subset=["x", "y"])
    if valid.empty:
        return {"spread": float("nan"), "ellipse_area": float("nan")}

    xs = valid["x"].to_numpy(dtype=float)
    ys = valid["y"].to_numpy(dtype=float)
    std_x = float(np.std(xs, ddof=0))
    std_y = float(np.std(ys, ddof=0))
    spread = float(np.hypot(std_x, std_y))

    ellipse_area = 0.0
    if valid.shape[0] >= 2:
        covariance = np.cov(np.column_stack((xs, ys)), rowvar=False, ddof=0)
        determinant = float(np.linalg.det(covariance))
        if determinant > 0.0:
            ellipse_area = float(np.sqrt(determinant))

    return {"spread": spread, "ellipse_area": ellipse_area}


def build_diversity_stats(frame: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, float]] = []
    for generation, group in frame.groupby("generation", sort=True):
        metrics = compute_diversity(group)
        rows.append(
            {
                "generation": int(generation),
                "spread": metrics["spread"],
                "ellipse_area": metrics["ellipse_area"],
            }
        )
    return pd.DataFrame(rows)


def set_offsets_3d(collection: object, frame: pd.DataFrame) -> None:
    if frame.empty:
        collection._offsets3d = (np.asarray([]), np.asarray([]), np.asarray([]))
        return
    collection._offsets3d = (
        frame["x"].to_numpy(dtype=float),
        frame["y"].to_numpy(dtype=float),
        frame["objective"].to_numpy(dtype=float),
    )


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    history_path = Path(args.history).resolve()
    history = load_history(history_path)
    prepared = prepare_history(history, args.pop_size)
    function_name = infer_function(history, args.function)
    fn = get_function(function_name)

    bounds_override = tuple(args.bounds) if args.bounds is not None else None
    xmin, xmax, ymin, ymax = infer_bounds(prepared, function_name, bounds_override)
    generations = sorted_generations(prepared, args.max_gens)

    x_grid = np.linspace(xmin, xmax, args.grid)
    y_grid = np.linspace(ymin, ymax, args.grid)
    xx, yy = np.meshgrid(x_grid, y_grid)
    zz = fn(xx, yy)

    frames: list[pd.DataFrame] = [
        prepared.loc[prepared["generation"] == generation].copy() for generation in generations
    ]
    top_frames = [select_top_k(frame, args.top_k) for frame in frames]
    best_rows = best_so_far_rows(prepared, generations)

    convergence = build_convergence_stats(prepared)
    convergence = convergence.loc[convergence["generation"].isin(generations)].reset_index(drop=True)
    diversity = build_diversity_stats(prepared)
    diversity = diversity.loc[diversity["generation"].isin(generations)].reset_index(drop=True)

    finite_objectives = prepared["objective"].to_numpy(dtype=float)
    finite_objectives = finite_objectives[np.isfinite(finite_objectives)]
    zmin = float(min(np.min(zz), np.min(finite_objectives)))
    zmax = float(max(np.max(zz), np.max(finite_objectives)))

    fig = plt.figure(figsize=(14, 8))
    grid = GridSpec(2, 2, width_ratios=[1.45, 1.0], height_ratios=[1.0, 1.0], figure=fig)
    ax3d = fig.add_subplot(grid[:, 0], projection="3d")
    ax_conv = fig.add_subplot(grid[0, 1])
    ax_div = fig.add_subplot(grid[1, 1])
    fig.subplots_adjust(top=0.93, wspace=0.28, hspace=0.32)

    ax3d.plot_surface(xx, yy, zz, cmap="viridis", alpha=0.42, linewidth=0.0, antialiased=True)
    ax3d.set_xlabel("x")
    ax3d.set_ylabel("y")
    ax3d.set_zlabel("objective")
    ax3d.set_xlim(xmin, xmax)
    ax3d.set_ylim(ymin, ymax)
    ax3d.set_zlim(zmin, zmax)
    ax3d.view_init(elev=args.elev, azim=args.azim)

    population = ax3d.scatter([], [], [], s=46, c="red", alpha=0.9, edgecolors="black", linewidths=0.5)
    top_marker = ax3d.scatter([], [], [], marker="*", s=180, c="gold", edgecolors="black", linewidths=0.9)
    best_marker = ax3d.scatter([], [], [], marker="o", s=140, c="white", edgecolors="black", linewidths=1.1)
    trail_line, = ax3d.plot([], [], [], color="white", alpha=0.45, linewidth=1.2, linestyle="--")
    generation_text = ax3d.text2D(
        0.02,
        0.98,
        "",
        transform=ax3d.transAxes,
        ha="left",
        va="top",
        bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none", "pad": 3.0},
    )

    conv_lines = {
        "best": ax_conv.plot(convergence["generation"], convergence["best"], linewidth=2.0, label="best")[0],
        "median": ax_conv.plot(convergence["generation"], convergence["median"], linewidth=1.6, label="median")[0],
        "worst": ax_conv.plot(convergence["generation"], convergence["worst"], linewidth=1.6, label="worst")[0],
        "best_so_far": ax_conv.plot(
            convergence["generation"], convergence["best_so_far"], linestyle="--", linewidth=1.8, label="best-so-far"
        )[0],
    }
    conv_marker = ax_conv.axvline(generations[0], color="black", linestyle=":", linewidth=1.5)
    ax_conv.set_title("Convergence")
    ax_conv.set_xlabel("generation")
    ax_conv.set_ylabel("objective")
    ax_conv.grid(True, alpha=0.25)
    ax_conv.legend(loc="upper right")

    div_lines = {
        "spread": ax_div.plot(diversity["generation"], diversity["spread"], linewidth=1.8, label="spread")[0],
        "ellipse_area": ax_div.plot(
            diversity["generation"], diversity["ellipse_area"], linewidth=1.8, label="ellipse_area"
        )[0],
    }
    div_marker = ax_div.axvline(generations[0], color="black", linestyle=":", linewidth=1.5)
    ax_div.set_title("Diversity")
    ax_div.set_xlabel("generation")
    ax_div.set_ylabel("diversity")
    ax_div.grid(True, alpha=0.25)
    ax_div.legend(loc="upper right")

    fig.suptitle(f"{function_name} evolutionary dashboard", fontsize=14)

    total_frames = len(generations)

    def clip_line(line: plt.Line2D, x_values: np.ndarray, y_values: np.ndarray, frame_index: int) -> None:
        line.set_data(x_values[: frame_index + 1], y_values[: frame_index + 1])

    conv_x = convergence["generation"].to_numpy(dtype=float)
    conv_y = {name: convergence[name].to_numpy(dtype=float) for name in conv_lines}
    div_x = diversity["generation"].to_numpy(dtype=float)
    div_y = {name: diversity[name].to_numpy(dtype=float) for name in div_lines}

    def init() -> tuple:
        empty = frames[0].iloc[0:0].copy()
        set_offsets_3d(population, empty)
        set_offsets_3d(top_marker, empty)
        set_offsets_3d(best_marker, empty)
        trail_line.set_data_3d([], [], [])
        generation_text.set_text("")
        ax3d.view_init(elev=args.elev, azim=args.azim)

        for name, line in conv_lines.items():
            line.set_data([], [])
        for name, line in div_lines.items():
            line.set_data([], [])
        conv_marker.set_xdata([generations[0], generations[0]])
        div_marker.set_xdata([generations[0], generations[0]])
        return (
            population,
            top_marker,
            best_marker,
            trail_line,
            generation_text,
            *conv_lines.values(),
            conv_marker,
            *div_lines.values(),
            div_marker,
        )

    def update(frame_number: int) -> tuple:
        generation = generations[frame_number]
        generation_frame = frames[frame_number]
        top_frame = top_frames[frame_number]
        best_row = best_rows[frame_number]

        set_offsets_3d(population, generation_frame)
        set_offsets_3d(top_marker, top_frame)

        if best_row is None:
            set_offsets_3d(best_marker, generation_frame.iloc[0:0].copy())
            trail_line.set_data_3d([], [], [])
        else:
            best_frame = pd.DataFrame([best_row])
            set_offsets_3d(best_marker, best_frame)
            trail_points = np.asarray(
                [
                    (float(row["x"]), float(row["y"]), float(row["objective"]))
                    for row in best_rows[: frame_number + 1]
                    if row is not None
                ],
                dtype=float,
            )
            if trail_points.size > 0:
                trail_line.set_data_3d(trail_points[:, 0], trail_points[:, 1], trail_points[:, 2])
            else:
                trail_line.set_data_3d([], [], [])

        if args.rotate:
            ax3d.view_init(elev=args.elev, azim=args.azim + frame_number * 2.0)

        generation_text.set_text(f"{function_name} Gen {generation} / {generations[-1]}")

        for name, line in conv_lines.items():
            clip_line(line, conv_x, conv_y[name], frame_number)
        for name, line in div_lines.items():
            clip_line(line, div_x, div_y[name], frame_number)

        conv_marker.set_xdata([generation, generation])
        div_marker.set_xdata([generation, generation])

        return (
            population,
            top_marker,
            best_marker,
            trail_line,
            generation_text,
            *conv_lines.values(),
            conv_marker,
            *div_lines.values(),
            div_marker,
        )

    anim = FuncAnimation(
        fig,
        update,
        init_func=init,
        frames=total_frames,
        interval=max(1, int(round(1000.0 / max(1, args.fps)))),
        blit=False,
    )

    out_path = resolve_output_path(args.out, history_path.parent)
    if out_path is None:
        raise ValueError("Failed to resolve output path.")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    suffix = out_path.suffix.lower()
    if suffix == ".gif":
        writer = PillowWriter(fps=args.fps)
    elif suffix == ".mp4":
        writer = FFMpegWriter(fps=args.fps)
    else:
        raise ValueError("Output extension must be .gif or .mp4")

    try:
        anim.save(out_path, writer=writer)
    except Exception as exc:
        if suffix == ".mp4":
            raise RuntimeError(
                "Failed to write MP4. Ensure ffmpeg is installed and discoverable by matplotlib, "
                "or use a .gif output path."
            ) from exc
        raise

    print(f"Saved animation: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
