#!/usr/bin/env python3
"""Plot population diversity metrics by generation from a history CSV."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def preparse_out_path() -> str | None:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--out", default=None)
    args, _ = parser.parse_known_args()
    return args.out


if preparse_out_path():
    import matplotlib

    matplotlib.use("Agg", force=True)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from output_paths import resolve_output_path

SUPPORTED_METRICS = ("std_x", "std_y", "spread", "ellipse_area")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot population diversity metrics by generation from history.csv."
    )
    parser.add_argument("--history", required=True, help="CSV generated by extract_history.py.")
    parser.add_argument(
        "--pop-size",
        type=int,
        default=None,
        help="Population size used to reconstruct generation from eval_index when needed.",
    )
    parser.add_argument("--out", default=None, help="PNG output path. If omitted, show interactively.")
    parser.add_argument("--title", default=None, help="Plot title.")
    parser.add_argument(
        "--metrics",
        default="std_x,std_y,spread,ellipse_area",
        help="Comma-separated metrics to plot. Supported: std_x,std_y,spread,ellipse_area",
    )
    parser.add_argument(
        "--logy",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Use logarithmic y-scale when all plotted values are positive (default: false).",
    )
    return parser.parse_args(argv)


def load_history(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    if frame.empty:
        raise ValueError("History CSV is empty.")
    return frame


def prepare_history(frame: pd.DataFrame, pop_size: int | None) -> pd.DataFrame:
    prepared = frame.copy()
    prepared["x"] = pd.to_numeric(prepared.get("x"), errors="coerce")
    prepared["y"] = pd.to_numeric(prepared.get("y"), errors="coerce")
    prepared["eval_index"] = pd.to_numeric(prepared.get("eval_index"), errors="coerce")

    if "generation" in prepared.columns:
        prepared["generation"] = pd.to_numeric(prepared["generation"], errors="coerce")
    else:
        if pop_size is None:
            raise ValueError(
                "History CSV does not contain a generation column. Provide --pop-size to reconstruct generations."
            )
        if pop_size < 1:
            raise ValueError("--pop-size must be >= 1")
        prepared["generation"] = np.floor_divide(prepared["eval_index"], pop_size)

    prepared = prepared.dropna(subset=["generation"]).copy()
    if prepared.empty:
        raise ValueError("No rows with generation information were found.")

    prepared["generation"] = prepared["generation"].astype(int)
    return prepared


def parse_metrics(value: str) -> list[str]:
    metrics = [item.strip() for item in value.split(",") if item.strip()]
    if not metrics:
        raise ValueError("No metrics were requested. Choose from: " + ", ".join(SUPPORTED_METRICS))
    unknown = [metric for metric in metrics if metric not in SUPPORTED_METRICS]
    if unknown:
        raise ValueError(
            "Unknown metrics: {}. Supported metrics: {}".format(
                ", ".join(unknown),
                ", ".join(SUPPORTED_METRICS),
            )
        )
    return metrics


def compute_generation_metrics(group: pd.DataFrame) -> pd.Series:
    valid = group.dropna(subset=["x", "y"])
    if valid.empty:
        return pd.Series(
            {"std_x": np.nan, "std_y": np.nan, "spread": np.nan, "ellipse_area": np.nan},
            dtype=float,
        )

    x_values = valid["x"].to_numpy(dtype=float)
    y_values = valid["y"].to_numpy(dtype=float)
    std_x = float(np.std(x_values, ddof=0))
    std_y = float(np.std(y_values, ddof=0))
    spread = float(np.hypot(std_x, std_y))

    ellipse_area = 0.0
    if valid.shape[0] >= 2:
        covariance = np.cov(np.column_stack((x_values, y_values)), rowvar=False, ddof=0)
        determinant = float(np.linalg.det(covariance))
        if determinant > 0.0:
            ellipse_area = float(np.sqrt(determinant))

    return pd.Series(
        {
            "std_x": std_x,
            "std_y": std_y,
            "spread": spread,
            "ellipse_area": ellipse_area,
        },
        dtype=float,
    )


def build_metrics(frame: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, float]] = []
    for generation, group in frame.groupby("generation", sort=True):
        metrics = compute_generation_metrics(group)
        rows.append(
            {
                "generation": int(generation),
                "std_x": float(metrics["std_x"]),
                "std_y": float(metrics["std_y"]),
                "spread": float(metrics["spread"]),
                "ellipse_area": float(metrics["ellipse_area"]),
            }
        )
    return pd.DataFrame(rows)


def should_use_log_scale(stats: pd.DataFrame, metrics: list[str], requested: bool) -> bool:
    if not requested:
        return False
    values = stats[metrics].to_numpy(dtype=float).ravel()
    finite_values = values[np.isfinite(values)]
    if finite_values.size == 0:
        return False
    if np.any(finite_values <= 0.0):
        print(
            "Warning: disabling log y-scale because one or more plotted diversity values are non-positive.",
            file=sys.stderr,
        )
        return False
    return True


def plot_metrics(stats: pd.DataFrame, metrics: list[str], title: str | None, logy: bool) -> plt.Figure:
    fig, ax = plt.subplots(figsize=(9, 6))

    for metric in metrics:
        ax.plot(stats["generation"], stats[metric], linewidth=1.8, label=metric)

    ax.set_xlabel("generation")
    ax.set_ylabel("diversity")
    ax.set_title(title or "Population diversity by generation")
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(loc="best")

    if logy:
        ax.set_yscale("log")

    fig.tight_layout()
    return fig


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    metrics = parse_metrics(args.metrics)
    history_path = Path(args.history).resolve()
    history = load_history(history_path)
    prepared = prepare_history(history, args.pop_size)
    stats = build_metrics(prepared)
    use_logy = should_use_log_scale(stats, metrics, args.logy)
    fig = plot_metrics(stats, metrics, args.title, use_logy)

    if args.out:
        out_path = resolve_output_path(args.out, history_path.parent)
        if out_path is None:
            raise ValueError("Failed to resolve output path.")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=160)
        print(f"Saved plot: {out_path}")
    else:
        plt.show()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
