#!/usr/bin/env python3
"""Plot per-generation convergence statistics from a history CSV."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def preparse_out_path() -> str | None:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--out", default=None)
    args, _ = parser.parse_known_args()
    return args.out


if preparse_out_path():
    import matplotlib

    matplotlib.use("Agg", force=True)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot best/median/worst objective by generation from history.csv."
    )
    parser.add_argument("--history", required=True, help="CSV generated by extract_history.py.")
    parser.add_argument(
        "--pop-size",
        type=int,
        default=None,
        help="Population size used to reconstruct generation from eval_index when needed.",
    )
    parser.add_argument("--out", default=None, help="PNG output path. If omitted, show interactively.")
    parser.add_argument("--title", default=None, help="Plot title.")
    parser.add_argument(
        "--logy",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Use logarithmic y-scale when all plotted values are positive (default: true).",
    )
    parser.add_argument(
        "--show-best-so-far",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Overlay cumulative best objective across generations (default: true).",
    )
    return parser.parse_args()


def load_history(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    if frame.empty:
        raise ValueError("History CSV is empty.")
    return frame


def prepare_history(frame: pd.DataFrame, pop_size: int | None) -> pd.DataFrame:
    prepared = frame.copy()
    prepared["objective"] = pd.to_numeric(prepared.get("objective"), errors="coerce")
    prepared["eval_index"] = pd.to_numeric(prepared.get("eval_index"), errors="coerce")

    if "generation" in prepared.columns:
        prepared["generation"] = pd.to_numeric(prepared["generation"], errors="coerce")
    else:
        if pop_size is None:
            raise ValueError(
                "History CSV does not contain a generation column. Provide --pop-size to reconstruct generations."
            )
        if pop_size < 1:
            raise ValueError("--pop-size must be >= 1")
        prepared["generation"] = np.floor_divide(prepared["eval_index"], pop_size)

    prepared = prepared.dropna(subset=["objective", "generation"]).copy()
    if prepared.empty:
        raise ValueError("No rows with numeric objective and generation information were found.")

    prepared["generation"] = prepared["generation"].astype(int)
    return prepared


def build_stats(frame: pd.DataFrame) -> pd.DataFrame:
    stats = (
        frame.groupby("generation", sort=True)["objective"]
        .agg(best="min", median="median", worst="max")
        .reset_index()
    )
    stats["best_so_far"] = stats["best"].cummin()
    return stats


def should_use_log_scale(stats: pd.DataFrame, requested: bool) -> bool:
    if not requested:
        return False
    values = stats[["best", "median", "worst", "best_so_far"]].to_numpy(dtype=float).ravel()
    finite_values = values[np.isfinite(values)]
    if finite_values.size == 0:
        return False
    if np.any(finite_values <= 0.0):
        print(
            "Warning: disabling log y-scale because one or more plotted values are non-positive.",
            file=sys.stderr,
        )
        return False
    return True


def plot_stats(stats: pd.DataFrame, title: str | None, logy: bool, show_best_so_far: bool) -> plt.Figure:
    fig, ax = plt.subplots(figsize=(9, 6))

    ax.plot(stats["generation"], stats["best"], linewidth=2.0, label="best")
    ax.plot(stats["generation"], stats["median"], linewidth=1.6, label="median")
    ax.plot(stats["generation"], stats["worst"], linewidth=1.6, label="worst")

    if show_best_so_far:
        ax.plot(stats["generation"], stats["best_so_far"], linestyle="--", linewidth=1.8, label="best-so-far")

    ax.set_xlabel("generation")
    ax.set_ylabel("objective")
    ax.set_title(title or "Convergence by generation")
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(loc="best")

    if logy:
        ax.set_yscale("log")

    fig.tight_layout()
    return fig


def main() -> int:
    args = parse_args()
    history = load_history(Path(args.history))
    prepared = prepare_history(history, args.pop_size)
    stats = build_stats(prepared)
    use_logy = should_use_log_scale(stats, args.logy)
    fig = plot_stats(stats, args.title, use_logy, args.show_best_so_far)

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=160)
        print(f"Saved plot: {out_path}")
    else:
        plt.show()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
