#!/usr/bin/env python3
"""Plot a single evolutionary population snapshot over an objective contour."""

from __future__ import annotations

import argparse
from pathlib import Path


def preparse_out_path() -> str | None:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--out", default=None)
    args, _ = parser.parse_known_args()
    return args.out


if preparse_out_path():
    import matplotlib

    matplotlib.use("Agg", force=True)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from functions_2d import get_bounds, get_function, infer_bounds_from_points


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot one generation of an evolutionary optimization history over an objective contour."
    )
    parser.add_argument("--history", required=True, help="CSV generated by extract_history.py.")
    parser.add_argument("--gen", type=int, required=True, help="Generation index to visualize.")
    parser.add_argument(
        "--pop-size",
        type=int,
        default=None,
        help="Population size used to reconstruct generation from eval_index when needed.",
    )
    parser.add_argument("--function", default=None, help="Function name override.")
    parser.add_argument(
        "--bounds",
        nargs=4,
        type=float,
        metavar=("xmin", "xmax", "ymin", "ymax"),
        default=None,
        help="Override plotting bounds.",
    )
    parser.add_argument("--grid", type=int, default=400, help="Contour grid resolution.")
    parser.add_argument("--out", default=None, help="PNG output path. If omitted, show interactively.")
    parser.add_argument("--title", default=None, help="Plot title.")
    parser.add_argument("--top-k", type=int, default=5, help="Number of best individuals to highlight.")
    parser.add_argument(
        "--mark-best-so-far",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Mark the best point seen up to and including the selected generation.",
    )
    return parser.parse_args()


def load_history(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    if frame.empty:
        raise ValueError("History CSV is empty.")
    return frame


def infer_function(frame: pd.DataFrame, override: str | None) -> str:
    if override:
        return override
    if "function" not in frame.columns:
        raise ValueError("Could not infer function from CSV. Use --function to specify one explicitly.")

    names = frame["function"].fillna("").astype(str).str.strip()
    non_empty = names[names != ""]
    if non_empty.empty:
        raise ValueError("Could not infer function from CSV. Use --function to specify one explicitly.")
    return str(non_empty.iloc[0])


def prepare_history(frame: pd.DataFrame, pop_size: int | None) -> pd.DataFrame:
    prepared = frame.copy()
    prepared["x"] = pd.to_numeric(prepared.get("x"), errors="coerce")
    prepared["y"] = pd.to_numeric(prepared.get("y"), errors="coerce")
    prepared["objective"] = pd.to_numeric(prepared.get("objective"), errors="coerce")
    prepared["eval_index"] = pd.to_numeric(prepared.get("eval_index"), errors="coerce")

    if "generation" in prepared.columns:
        prepared["generation"] = pd.to_numeric(prepared["generation"], errors="coerce")
    else:
        if pop_size is None:
            raise ValueError(
                "History CSV does not contain a generation column. Provide --pop-size to reconstruct generations."
            )
        if pop_size < 1:
            raise ValueError("--pop-size must be >= 1")
        prepared["generation"] = np.floor_divide(prepared["eval_index"], pop_size)

    prepared = prepared.dropna(subset=["x", "y", "generation"]).copy()
    if prepared.empty:
        raise ValueError("No rows with numeric x/y and generation information were found.")

    prepared["generation"] = prepared["generation"].astype(int)
    return prepared


def infer_bounds(
    frame: pd.DataFrame,
    function_name: str,
    override: tuple[float, float, float, float] | None,
) -> tuple[float, float, float, float]:
    if override is not None:
        return override
    try:
        return get_bounds(function_name)
    except ValueError:
        pass
    return infer_bounds_from_points(frame["x"].to_numpy(dtype=float), frame["y"].to_numpy(dtype=float))


def select_generation(frame: pd.DataFrame, generation: int) -> pd.DataFrame:
    subset = frame.loc[frame["generation"] == generation].copy()
    if subset.empty:
        available = sorted(frame["generation"].unique().tolist())
        raise ValueError(f"Generation {generation} not found in history. Available generations: {available}")
    return subset


def select_top_k(frame: pd.DataFrame, top_k: int) -> pd.DataFrame:
    if top_k <= 0:
        return frame.iloc[0:0].copy()
    ordered = frame.sort_values(by="objective", ascending=True, na_position="last", kind="mergesort")
    return ordered.head(top_k).copy()


def select_best_so_far(frame: pd.DataFrame, generation: int) -> pd.Series | None:
    candidates = frame.loc[frame["generation"] <= generation].copy()
    candidates = candidates.dropna(subset=["objective"])
    if candidates.empty:
        return None
    ordered = candidates.sort_values(by="objective", ascending=True, na_position="last", kind="mergesort")
    return ordered.iloc[0]


def main() -> int:
    args = parse_args()
    history = load_history(Path(args.history))
    prepared = prepare_history(history, args.pop_size)

    function_name = infer_function(history, args.function)
    # Reuse the centralized function registry so the contour matches the evaluator.
    fn = get_function(function_name)

    bounds_override = tuple(args.bounds) if args.bounds is not None else None
    xmin, xmax, ymin, ymax = infer_bounds(prepared, function_name, bounds_override)

    generation_frame = select_generation(prepared, args.gen)
    highlighted = select_top_k(generation_frame, args.top_k)
    best_so_far = select_best_so_far(prepared, args.gen) if args.mark_best_so_far else None

    x_grid = np.linspace(xmin, xmax, args.grid)
    y_grid = np.linspace(ymin, ymax, args.grid)
    xx, yy = np.meshgrid(x_grid, y_grid)
    zz = fn(xx, yy)

    fig, ax = plt.subplots(figsize=(9, 7))
    ax.contourf(xx, yy, zz, levels=50)

    scatter = ax.scatter(
        generation_frame["x"],
        generation_frame["y"],
        c=generation_frame["objective"],
        cmap="viridis",
        s=55,
        alpha=0.9,
        edgecolors="black",
        linewidths=0.6,
        label=f"generation {args.gen}",
    )
    fig.colorbar(scatter, ax=ax, label="objective")

    if not highlighted.empty:
        ax.scatter(
            highlighted["x"],
            highlighted["y"],
            marker="*",
            s=220,
            facecolors="gold",
            edgecolors="black",
            linewidths=0.9,
            label=f"top {min(args.top_k, len(highlighted))}",
        )

    if best_so_far is not None:
        ax.scatter(
            [float(best_so_far["x"])],
            [float(best_so_far["y"])],
            marker="o",
            s=160,
            facecolors="white",
            edgecolors="black",
            linewidths=1.2,
            label=f"best-so-far ({best_so_far['objective']:.6g})",
        )

    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, ymax)
    ax.set_title(args.title or f"{function_name} population snapshot (generation {args.gen})")
    ax.legend(loc="best")
    fig.tight_layout()

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=160)
        print(f"Saved plot: {out_path}")
    else:
        plt.show()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
